# Generated by Django 5.1 on 2024-09-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_short_desc_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_disc',
            field=models.TextField(null=True),
        ),
    ]
