# Generated by Django 5.1 on 2024-09-24 03:02

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_short_disc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=shop.models.category_image_upload_path),
        ),
    ]
