# Generated by Django 5.1 on 2024-09-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_name',
            field=models.TextField(null=True),
        ),
    ]
