# Generated by Django 5.1.1 on 2024-10-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
